// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXw3hU3rtqROCGIyU0Glueykcbkb8NxfA',
    appId: '1:388488627408:web:e76efb63ad63ee3fa58ad5',
    messagingSenderId: '388488627408',
    projectId: 'talknest-a8a6c',
    authDomain: 'talknest-a8a6c.firebaseapp.com',
    storageBucket: 'talknest-a8a6c.firebasestorage.app',
    measurementId: 'G-JCBM7L36HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkVt8qVMP3W8UwgXKF3js3LJebHKQPxJI',
    appId: '1:388488627408:android:beda8c89fc7db4a7a58ad5',
    messagingSenderId: '388488627408',
    projectId: 'talknest-a8a6c',
    storageBucket: 'talknest-a8a6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUCELd0WSaMjdrfdWUrkWX45d4harTjJc',
    appId: '1:388488627408:ios:c3775de02f3ddd5ea58ad5',
    messagingSenderId: '388488627408',
    projectId: 'talknest-a8a6c',
    storageBucket: 'talknest-a8a6c.firebasestorage.app',
    iosBundleId: 'com.cgg.gov.sampleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUCELd0WSaMjdrfdWUrkWX45d4harTjJc',
    appId: '1:388488627408:ios:c3775de02f3ddd5ea58ad5',
    messagingSenderId: '388488627408',
    projectId: 'talknest-a8a6c',
    storageBucket: 'talknest-a8a6c.firebasestorage.app',
    iosBundleId: 'com.cgg.gov.sampleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXw3hU3rtqROCGIyU0Glueykcbkb8NxfA',
    appId: '1:388488627408:web:0815f0f5283dbae5a58ad5',
    messagingSenderId: '388488627408',
    projectId: 'talknest-a8a6c',
    authDomain: 'talknest-a8a6c.firebaseapp.com',
    storageBucket: 'talknest-a8a6c.firebasestorage.app',
    measurementId: 'G-WPXTZEZGGS',
  );

}